# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

php:
  - 5.2
  - 5.3
  - 5.5

env:
  - WP_VERSION=nightly WP_MULTISITE=0

matrix:
  include:
    - php: 5.2
      env: WP_VERSION=nightly WP_MULTISITE=1

cache:
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules

before_install:
  # set up WP install
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - git clone --depth=1 git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  # set up tests config
  - cd $WP_DEVELOP_DIR
  - echo $WP_DEVELOP_DIR
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  # set up database
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
  # prepare for running the tests
  - cd $TRAVIS_BUILD_DIR
  - npm install -g grunt-cli

# Clones WordPress and configures our testing environment.
before_script:
  # Setup Coveralls
  - phpenv local 5.5
  - composer self-update
  - composer install --no-interaction
  - phpenv local --unset

script:
  # No need for this now
  # bash bin/phpcs.sh
  - phpunit --coverage-clover clover.xml

after_script:
  # Push coverage off to Codecov
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1
